{{- if .Values.scheduling.userScheduler.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "jupyterhub.user-scheduler-deploy.fullname" . }}
  labels:
    {{- include "jupyterhub.labels" . | nindent 4 }}
data:
  {{- /*
    This is configuration of a k8s official kube-scheduler binary running in the
    user-scheduler pod.

    ref: https://kubernetes.io/docs/reference/scheduling/config/
    ref: https://kubernetes.io/docs/reference/config-api/kube-scheduler-config.v1beta3/
    ref: https://kubernetes.io/docs/reference/config-api/kube-scheduler-config.v1/

    kubescheduler.config.k8s.io/v1beta3 requires kube-scheduler binary version >=1.23
    kubescheduler.config.k8s.io/v1 requires kube-scheduler binary version >=1.25

    FIXME: Add logic to transition from v1beta3 to v1 if its supported.
           v1beta3 is likeley to be removed in k8s 1.27.
  */}}
  config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta3
    kind: KubeSchedulerConfiguration
    leaderElection:
      resourceLock: endpoints
      resourceName: {{ include "jupyterhub.user-scheduler-lock.fullname" . }}
      resourceNamespace: "{{ .Release.Namespace }}"
    profiles:
      - schedulerName: {{ include "jupyterhub.user-scheduler.fullname" . }}
        {{- with .Values.scheduling.userScheduler.plugins }}
        plugins:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
        {{- with .Values.scheduling.userScheduler.pluginConfig }}
        pluginConfig:
          {{- . | toYaml | nindent 10 }}
        {{- end }}
{{- end }}
